### PR TITLE
Added boats for inspection list

### LINKED ISSUE #19: Add boat list, available for inspection
Boat list should be sorted by first inspected (the one that was inspected the longest time ago) or by geographical position.
image

### PR DESCRIPTION
**Pull request by aayaffe**
Added boat club to add boat activity
Added boats for inspection list
Removed unused and bad functions from iDb
Closed #19

### CODE REVIEW

**Comment by motim6026** [comment]
OK

**Comment by aayaffe** [comment]
Have you pulled it and try to run it?
Did you review any of the changes?

**Comment by motim6026** [comment]
No sorry, ill do it now.

בתאריך 30 בדצמ׳ 2017 9:33 אחה״צ,‏ "aayaffe" <notifications@github.com> כתב:

**Comment by motim6026** [comment]
way when the user create new boat, the button "add boat" turn off?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by motim6026** [comment]
I think we need to add to the user's variables the number of points he has

**Comment by aayaffe** [comment]
You are correct.
I think that for the first versions we should stick to one boat per user.
More than one boat per user is quite rare and I would not want to support
it currently.

**Comment by aayaffe** [comment]
Again you are correct, but there are many things we need to add.
We will add them as necessary and with the feature requiring it.

**Pull request merged**
